void setupPatterns();
void pattern1();
void pattern2();
void pattern3();
void pattern4();
void pattern5();
void pattern6();
void pattern7();
void displayPattern(int patternNumber);
void setBrightness(int level);